### ISSUE TITLE
Make the main table easier to read...

### ISSUE THREAD

**Issue by rodrigograca31** [jgthms/html-reference#5]
Hi!

I'm not sure if it conflicts with other CSSs in other pages because I don't know the project but this works for the main/index page:
```css
#finder-list .finder-item:nth-child(even) {
    background: #CCC;
}
```

Regards, Rodrigo.
